webtalk_init -webtalk_dir D:\\dario\\fulgor\\workspace_tp8\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-10-29 01:02:00" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211967778_0_0_162" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "sketm0oga4m7jqp9g7f6041sra" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_17" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A10-9700 RADEON R7, 10 COMPUTE CORES 4C+6G " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3493 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.514 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "NA" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key RecordType -value "ToolUsage" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key BOOTGEN_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key FLASH_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key MOVE_APP_TO_SYSTEM_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key SDX_EXPORT_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key SDX_IMPORT_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key SDX_BUILD_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key SDX_NO_OP_BUILD_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key TCF_APP_DEBUG_count -value "3" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key TCF_SYSTEM_DEBUG_count -value "3" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key GDB_DEBUG_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key QEMU_DEBUG_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key ESTIMATION_DEBUG_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key SDSOC_TRACE_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key PERFORMANCE_ANALYSIS_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key SPM_ANALYSIS_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key CROSS_TRIGGER_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key TCF_PROFILER_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key APPLICATION_PLATFORM_CHANGE_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key APPLICATION_SYS_CONFIG_CHANGE_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_add_data -client vitis -key SYSTEM_PLATFORM_CHANGE_count -value "0" -context "vitis\\\\tool/1603944120311"
webtalk_transmit -clientid 2324637102 -regid "211967778_0_0_162" -xml D:\\dario\\fulgor\\workspace_tp8\\webtalk\\usage_statistics_ext_vitis.xml -html D:\\dario\\fulgor\\workspace_tp8\\webtalk\\usage_statistics_ext_vitis.html -wdm D:\\dario\\fulgor\\workspace_tp8\\webtalk\\vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
